### ISSUE TITLE
[REQ] Expand query trace definition to include VertiPaq SE Query/Cache Match

### ISSUE THREAD

**Issue by byobi** [marcosqlbi/SsasEventsAnalyzer#7]
Expanding the xevent query trace to include the following events... 
- VertiPaq SE Query End
- VertiPaq SE Query Cache Match

would allow us to provide deeper insights into query performance issues...
- SE vs FE bottleneck
- number of SE queries (cached vs non-cached)
- number of SE queries w/ "callbacks"

However, on busy systems, this could potentially add a lot more data to the xevent files and overwhelm the current method for shredding the xevent files (i.e. sys.fn_xe_file_target_read_file). If that becomes the case we would need to explore other options... for example, using .NET (http://byobi.com/blog/2015/12/3-methods-for-shredding-analysis-services-extended-events/)

**Comment by marcosqlbi** [comment]
I would avoid capturing those events by default. Analyzing the VertiPaq events is convenient when using DAX Studio, I'm not sure that such analysis on historical query have an high value, but it certainly have an high cost. A single DAX query can raise tens or hundreds of SE queries. I'm not saying it wouldn't be interesting, just that it's expensive to capture and not easy to analyze later.

**Comment by byobi** [comment]
yes, that's a good point... the collection/storage/processing is very likely to out-weigh the analysis value. Plus, from a usage standpoint, slow queries will have to be brought over to DAX studio for proper tuning... so yeah, agree there's not much value with this suggestion.
